### ISSUE TITLE
CarrouselList Todo

### ISSUE THREAD

**Issue by M1zz** [M1zz/SwiftUIViewFactory#1]
- [ ] add network manager
- [ ] add textField delegate
- [ ] add open to safari click read more button
- [ ] add read me
